### ISSUE TITLE
Alternate splash image

### ISSUE THREAD

**Issue by ghost** [redsPL/libbieoffice#3]
Not an issue per-say, but here's another image

![libre_office](https://user-images.githubusercontent.com/12851254/32978069-5ccdba4e-cc08-11e7-8e7f-27913d5ae730.png)

Also, for the joke:

![libbe_office](https://user-images.githubusercontent.com/12851254/32978063-42d55dae-cc08-11e7-991c-61899897279f.png)

**Comment by sdomi** [comment]
I can include the first one as an alternative (installed with --splash=alt or something like that), but the second one.. It's pronounced Libbie, you know?

**Comment by ghost** [comment]
Wow, I double checked and still messed it up.

**Comment by sdomi** [comment]
I've just added your first image to the repo, it's installable by executing
`./libbie.sh --splash alt`.
If you want your second splash to be available, fix the typo and create a merge request, adding it to /splash/ directory with an apropriate name (something like alt_libbie.png will do)
