### ISSUE TITLE
Doesn't work if LibreOffice uses `/usr/lib64`

### ISSUE THREAD

**Issue by pavelbraginskiy** [redsPL/libbieoffice#4]
`libbie.sh` looks for `intro.png` in `/usr/lib/libreoffice`, however on some systems, such as Fedora, libreoffice uses `/usr/lib64/libreoffice`.

**Comment by sdomi** [comment]
I've fixed it an hour ago, can you verify that it *is* working correctly?

**Comment by sdomi** [comment]
I have verified that it works, closing the issue.

BTW, thanks for reporting this fault, i appreciate it! :P

**Comment by pavelbraginskiy** [comment]
NP. I tried it myself too, worked fine.
